content-types:
  "application/vnd.ft-upp-live-blog-post+json":
    mapper: "spark"
    end-point: "http://upp-live-blog-post-validator:8080"
  "application/vnd.ft-upp-article+json":
    mapper: "spark"
    end-point: "http://upp-content-validator:8080http://upp-content-validator:8080"
  "application/vnd.ft-upp-content-placeholder+json":
    mapper: "spark"
    end-point: "http://upp-content-validator:8080"
  "application/json":
    mapper: "methode"
    end-point: "http://methode-article-mapper:8080"
end-point-health-checks:
  "http://upp-live-blog-post-validator:8080":
    id: "check-draft-upp-live-blog-validator"
    business-impact: "Draft spark content placeholder cannot be provided for suggestions"
    name: "Check upp-live-blog-validator service"
    panic-guide: "https://runbooks.in.ft.com/draft-content-api"
    severity: 1
    technical-summary: "Live blog content validator is not available at %v"
    checker-name: "Draft content upp-live-blog-validator"
  "http://upp-content-validator:8080":
    id: "check-draft-upp-content-validator"
    business-impact: "Draft spark content cannot be provided for suggestions"
    name: "Check upp-content-validator service"
    panic-guide: "https://runbooks.in.ft.com/draft-content-api"
    severity: 1
    technical-summary: "Draft upp content validator is not available at %v"
    checker-name: "Draft content upp-content-validator"
  "http://upp-content-placeholder-validator:8080":
    id: "check-draft-upp-content-placeholder-validator"
    business-impact: "Draft spark content placeholder cannot be provided for suggestions"
    name: "Check upp-content-validator service"
    panic-guide: "https://runbooks.in.ft.com/draft-content-api"
    severity: 1
    technical-summary: "Draft upp content validator is not available at %v"
    checker-name: "Draft content upp-content-placeholder-validator"
  "http://methode-article-mapper:8080":
    id: "check-draft-content-mapper"
    business-impact: "Draft methode content cannot be provided for suggestions"
    name: "Check draft content mapper service"
    panic-guide: "https://runbooks.in.ft.com/draft-content-api"
    severity: 1
    technical-summary: "Draft content mapper is not available at %v"
    checker-name: "Draft content methode-article-mapper"
