service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  hasOpenAPI: "true"

originID: "methode-web-pub|cct|spark-lists|spark"

allowedContentTypes:
  methodeContentType : "application/json"
  sparkArticleContentType: "application/vnd.ft-upp-article+json"
  sparkCPHContentType: "application/vnd.ft-upp-content-placeholder+json"
  sparkLiveBlogPostContentType: "application/vnd.ft-upp-live-blog-post+json application/vnd.ft-upp-live-blog-post-internal+json"

replicaCount: 2
image:
  repository: coco/draft-content-api
  pullPolicy: Always
resources:
  requests:
    memory: 10Mi
  limits:
    memory: 128Mi
