# Default values for draft-content-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  hasOpenAPI: "true"
replicaCount: 2
image:
  repository: coco/draft-content-api
  pullPolicy: IfNotPresent
#resources:
#  limits:
#    memory: 256Mi
ingress:
  host_pre_prod_eu: "pre-prod-eu-pac.ft.com"
  host_pre_prod_us: "pre-prod-us-pac.ft.com"
  host: "pre-prod-pac.ft.com"


