service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  hasOpenAPI: "true"

originID: "methode-web-pub|cct|spark-lists|spark"

# test: check whether is able to load it as var env
DraftConfig:
  methode: "methode|http://methode-article-mapper:8080|application/json"
  article: "article|http://upp-content-validator:8080|application/vnd.ft-upp-article+json"
  CPH: "CPH|http://upp-content-placeholder-validator:8080|application/vnd.ft-upp-content-placeholder+json"

#methodeDraftConfig: "http://methode-article-mapper:8080|application/json"
#articleDraftConfig: "http://upp-content-validator:8080|application/vnd.ft-upp-article+json"
#CPHDraftConfig: "http://upp-content-placeholder-validator:8080|application/vnd.ft-upp-content-placeholder+json"

eksCluster: false

replicaCount: 2
image:
  repository: coco/draft-content-api
  pullPolicy: Always
resources:
  requests:
    memory: 10Mi
  limits:
    memory: 128Mi
